<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions xmlns:extns="http://www.example.org/schema/1576710317531" xmlns:tns="http://www.example.org/wsdl/1576710317451" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="Calculator" targetNamespace="http://www.example.org/wsdl/1576710317451">
  <wsdl:import namespace="http://www.example.org/schema/1576710317531"/>
  <wsdl:message name="addRequest">
    <wsdl:part element="extns:addRequest" name="parameters"/>
  </wsdl:message>
  <wsdl:message name="addResponse">
    <wsdl:part element="extns:addResponse" name="parameters"/>
  </wsdl:message>
  <wsdl:portType name="Calculator">
    <wsdl:operation name="add">
      <wsdl:input message="tns:addRequest" name="addInput"/>
      <wsdl:output message="tns:addResponse" name="addOutput"/>
    </wsdl:operation>
  </wsdl:portType>
</wsdl:definitions>
